name: topfit
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.10.0
  - scikit-learn>=0.23.1
  - xgboost=1.5.0
  - scipy>=1.4.1
  - biopython>=1.79
  - numpy>=1.19.5
  - h5py>=2.10.0
  - hyperopt=0.2.2
  - pandas>=1.1.2
  - tqdm=4.32.1
  - gudhi>=3.3.0
